### ISSUE TITLE
simulate typing and make driver public

### ISSUE THREAD

**Issue by antonkulaga** [johanandren/scalenium#6]
I would like to test type suggestions in my select controls, is it possible to simulate focus and keyup/down events in scalenium? I also want to simulate some drag and drops but I do not see any mouseenter/mouseleave/mousewheel functions in both $ and the browser.
The only way that I see now is using webdriver directly as it has sendKeys method, but it is protected and you made Browser final for some weird reason :=(((((

**Comment by johanandren** [comment]
Since you provide the Scalenium Browser instance with the driver when you create your instance of it there shouldn't be a problem for you to get access to the driver and use whatever non-scalenium-wrapped operations on it you want. The reason why Browser is final and driver protected is to limit the amount of contact surface with code that uses the library to exactly the things that the library is meant to provide. (If you write libraries and not do this, you get big problems changing anything after your first release.)

That being said, it sounds reasonable to provide a Scala-ified API for focus and keyup and keydown unless they can already be achieved some other way through the current API. I don't think they would belong in the JQuery-like API, maybe rather a new trait with input device operations.

Since you made two requests in one, one of which will not be done, I will close this ticket and create a new one with only adding the mouse and keyboard interactions.
